// Generated by Wrangler by running `wrangler types`

interface Env {
  BETTER_AUTH_URL: "http://localhost:8787";
  EXTENSION_ORIGIN: "chrome-extension://gjkdmhmhmoahlkpcmkedpdjpahjkciip";
  BETTER_AUTH_SECRET: string;
  DB: D1Database;
}
